name: xshop
description: "XShop is a modern cross-platform fashion e-commerce application built with Flutter for Android, iOS, and Web, powered by Medusa.js as a headless commerce backend."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.3.0
  lucide_icons_flutter: ^3.1.15
  mix: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/brand/
    - assets/images/icons/
    - assets/images/onboarding/
  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/general_sans/Fonts/TTF/GeneralSans-Variable.ttf
        - asset: assets/fonts/general_sans/Fonts/TTF/GeneralSans-VariableItalic.ttf
          style: italic
